Port to 1.20.5-rc1
emilyploszaj/emi pull request #518
Opened 2024-04-18 20:34 UTC by embeddedt

Almost certainly contains bugs. However, it gets into the game, and some special recipes I checked manually (potions, anvil) seem to be working, so I believe it's correct for the most part.

The Neo project is temporarily disabled.

2024-04-19 02:52 UTC, emilyploszaj reviewed
Thanks, this is mostly looking good. Especially all the generated recipes, that looks like a pain.

Before merging this I should abstract some things in the general codebase to make merges more painless. The current list is:

Probably remove all self API mixins in later versions for sanity reasons.
`EmiPort.setPotion` similar to your `EmiUtil.setPotion`
`Comparison.compareNbt` should be phased out of impl usage because of the version name change, using an `EmiPort` method instead.
`EmiPort.getBasicTooltip(ItemStack)`
`EmiPort.isDamageable(Item)`
`EmiPort.canCombine(ItemStack, ItemStack)`

If you think anything should be added it'd be good to know, in the meantime I'll work on these changes so we can rebase and get this merged to a new branch.

2024-04-19 02:52 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/mixin/ClientConfigurationNetworkHandlerMixin.java
> +        EmiReloadManager.reloadTags();
Why are there two mixins that call `EmiReloadManager.reloadTags()`? EMI reloads once both tags and recipes are received and if multiple are called or in peculiar orders it may cause improper reloading behavior.

2024-04-19 02:52 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/mixin/SynchronizeRecipesS2CPacketMixin.java
> +
Why is this class empty?

2024-04-19 02:52 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/mixin/api/EmiStackMixin.java
> -		return new FluidEmiStack(fluid.getFluid(), fluid.getNbt());
anything in the `dev.emi.emi.mixin.api` package can be deleted without consequence, frankly all of the classes should probably be deleted in 1.20 and up, but deleting any errant classes here is not a problem.

2024-04-19 02:52 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/platform/fabric/EmiAgnosFabric.java
> -						if (potion == Potions.EMPTY) {
Why is this check removed?

2024-04-19 02:52 UTC, emilyploszaj commented on gradle.properties
> -enabled_platforms=fabric,neoforge
Does neo really not have any rc builds out yet?

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/EmiPort.java
> +	public static BannerPatternsComponent addRandomBanner(BannerPatternsComponent patterns, Random random, DynamicRegistryManager registryManager) {
EmiPort exists to reduce commit diffs, changing the signature here makes this goal useless. The dynamic registry manager should just be gotten implicitly inside this method, and the added method does not seem to be used elsewhere, so it can be removed.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/EmiUtil.java
> +	public static ItemStack setPotion(ItemStack stack, RegistryEntry<Potion> potion) {
This is likely more applicable for EmiPort and would need to be a separate base commit.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/VanillaPlugin.java
> +		List<Item> dyeableItems = EmiUtil.values(ItemTags.DYEABLE).map(RegistryEntry::value).collect(Collectors.toList());
This probably makes more sense as a base abstraction rather than a version diff.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/VanillaPlugin.java
> +		List<Item> dyeableItems = EmiUtil.values(ItemTags.DYEABLE).map(RegistryEntry::value).collect(Collectors.toList());
Additionally, is it reasonable to go based on the item tag rather than iterate the registry and collect everything that supports this interface/component?

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/VanillaPlugin.java
> +		for (Item i : EmiUtil.values(ItemTags.DYEABLE).map(RegistryEntry::value).collect(Collectors.toList())) {
This should probably be passed in from earlier, not ad hoc duplicate construction.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/Comparison.java
> +	private static final Comparison COMPARE_NBT = Comparison.compareData(stack -> stack.getComponents());
This constant and the method that returns it should probably be called "compare components". Any uses of this in EMI imply should probably additionally use an abstraction method to avoid version diffs.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/EmiStack.java
> +public abstract class EmiStack implements EmiIngredient, ComponentHolder {
What are the implications of implementing `ComponentHolder`?

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/ItemEmiStack.java
> +		return getItemStack().getTooltip(Item.TooltipContext.DEFAULT, client.player, TooltipType.BASIC);
Might be time to bite the bullet and add an `EmiPort.getTooltip(ItemStack)`

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/jemi/JemiUtil.java
> +			throw new UnsupportedOperationException("TODO port to components");
I'd prefer a more elegant error message like "Update JEMI integration with new JEI implementation" and more soft failure rather than hard failure.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/jemi/impl/JemiIngredientAcceptor.java
> +		if(true) throw new UnsupportedOperationException("TODO port to components");
Unrelated to earlier exception comments, `if(true)` is a style violation and code smell here

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/mixin/HandledScreenMixin.java
> +			target = "Lnet/minecraft/client/gui/screen/ingame/HandledScreen;drawBackground(Lnet/minecraft/client/gui/DrawContext;FII)V",
This is a malformed invoke descriptor. Mixin will accept it, but for consistency my style uses proper formatting with `.` and no `L`.

2024-04-19 02:52 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/recipe/special/EmiArmorDyeRecipe.java
> -	public static final List<Item> DYEABLE_ITEMS = EmiPort.getItemRegistry().stream()
This removal can likely be abstracted.

2024-04-19 06:06 UTC, emilyploszaj commented
I believe I've done a majority of the abstractions, actually decided against a few I listed in the review comment because of how few usages there were or complexity with the abstraction. This should be a more reasonable base to work against.

2024-04-19 13:58 UTC, embeddedt commented on fabric/src/main/java/dev/emi/emi/mixin/ClientConfigurationNetworkHandlerMixin.java
> +        EmiReloadManager.reloadTags();
Tags now seem to be synchronized in the configuration listener as well as the play listener; without having the mixin here, it doesn't detect tags being synced at all on initial load.

2024-04-19 13:59 UTC, embeddedt commented on fabric/src/main/java/dev/emi/emi/platform/fabric/EmiAgnosFabric.java
> -						if (potion == Potions.EMPTY) {
`Potions.EMPTY` no longer exists.

2024-04-19 13:59 UTC, embeddedt commented on gradle.properties
> -enabled_platforms=fabric,neoforge
Well, *now* we do, but it wasn't ready when I ported this yesterday. :laughing: I'll look into that.

2024-04-19 14:18 UTC, embeddedt commented on xplat/src/main/java/dev/emi/emi/VanillaPlugin.java
> +		List<Item> dyeableItems = EmiUtil.values(ItemTags.DYEABLE).map(RegistryEntry::value).collect(Collectors.toList());
> is it reasonable to go based on the item tag rather than iterate the registry and collect everything that supports this interface/component?

I don't think iterating the registry can work, because (from what I can tell) items do not define a set of supported components, only a set of default components (and I don't think the dyeable items necessarily have the dye component attached by default).

2024-04-19 14:21 UTC, embeddedt commented on xplat/src/main/java/dev/emi/emi/api/stack/EmiStack.java
> +public abstract class EmiStack implements EmiIngredient, ComponentHolder {
`ComponentHolder` just defines `ComponentMap getComponents()`, the rest of the methods are default wrappers that delegate to the component map. Main reason I implemented it was for "nice" QoL methods like `getOrDefault`.

2024-04-19 14:22 UTC, embeddedt commented on xplat/src/main/java/dev/emi/emi/mixin/HandledScreenMixin.java
> +			target = "Lnet/minecraft/client/gui/screen/ingame/HandledScreen;drawBackground(Lnet/minecraft/client/gui/DrawContext;FII)V",
Really? Almost all mods I have seen (and the MinecraftDev plugin, which has had contributions from people who developed Mixin in the past) generate the target descriptors this way. Interested to know more.

2024-04-19 14:23 UTC, embeddedt commented on fabric/src/main/java/dev/emi/emi/mixin/SynchronizeRecipesS2CPacketMixin.java
> +
I'm not sure the patch can still apply easily to 1.20.5; the recipe packet appears to have changed and now uses packet codecs. Wanted to leave the class here so that it would be more obvious during review. Not sure what you want to do with it.

2024-04-20 17:37 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/mixin/SynchronizeRecipesS2CPacketMixin.java
> +
Yeah the class can be deleted then

2024-04-20 17:38 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/VanillaPlugin.java
> +		List<Item> dyeableItems = EmiUtil.values(ItemTags.DYEABLE).map(RegistryEntry::value).collect(Collectors.toList());
Ah that makes sense, well then the tag will have to do

2024-04-20 17:38 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/EmiStack.java
> +public abstract class EmiStack implements EmiIngredient, ComponentHolder {
Good to know, I agree

2024-04-20 17:38 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/ItemEmiStack.java
> +		return getItemStack().getTooltip(Item.TooltipContext.DEFAULT, client.player, TooltipType.BASIC);
Decided this was too much of a pain

2024-04-20 17:43 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/mixin/HandledScreenMixin.java
> +			target = "Lnet/minecraft/client/gui/screen/ingame/HandledScreen;drawBackground(Lnet/minecraft/client/gui/DrawContext;FII)V",
mcdev is not an official plugin and it just so happens to use the "less correct" method of specifying descriptors. In the JVM constant pool, specifying a "type" is redundantly broad, because methods will always be called on classes, invokes are dot separated class/descriptor pairs. Technically, it'd be most correct to use `foo/Bar.baz:()V` with a colon but I'm both not sure if mixin supports that and honestly I don't think it looks good, plus it's non-ambiguous without it. The reason most people do it the wrong way is because, well, most people did it the wrong way and copy paste is how we survive as a society. It is simply more convenient to teach people "when you type in a class, always surround it with an L and a ; for some reason" rather than making the distinction between method invokes type usage. I have a weird bone to pick with this and it saves me one precious utf8 byte :P

2024-04-20 20:21 UTC, emilyploszaj reviewed
Did another pass, there still are a handful of outstanding things I mentioned the first time unfixed.

2024-04-20 20:21 UTC, emilyploszaj commented on fabric/src/main/java/dev/emi/emi/mixin/ClientConfigurationNetworkHandlerMixin.java
> +        EmiReloadManager.reloadTags();
I see, I'll keep this open as a reminder for me to take a deeper look into it after I merge.

2024-04-20 20:21 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/serializer/EmiStackSerializer.java
> +	EmiStack create(Identifier id, ComponentChanges componentPatch, long amount);
why componentPatch here

2024-04-20 20:21 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/platform/EmiAgnos.java
> +	public static List<Text> getFluidTooltip(Fluid fluid, ComponentChanges nbt) {
All these EmiAgnos methods still say `nbt`

2024-04-23 00:12 UTC, emilyploszaj requested changes
This is pretty close, I've made some new comments for things that need to get fixed and will push a commit with some final abstractions like I mentioned with the dyes.

2024-04-23 00:12 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/EmiPort.java
> +	public static ItemStack setPotion(ItemStack stack, RegistryEntry<Potion> potion) {
This extra method with registry entries shouldn't exist

2024-04-23 00:12 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/EmiPort.java
> +	public static @Nullable DynamicRegistryManager getRegistryManager() {
This new method shouldn't exist unless it's across all versions, which it can't be.

2024-04-23 00:12 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/EmiUtil.java
> +	public static ItemStack setPotion(ItemStack stack, RegistryEntry<Potion> potion) {
This is still present despite being in EmiPort

2024-04-23 00:12 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/Comparison.java
> +	private static final Comparison COMPARE_NBT = Comparison.compareData(stack -> stack.getComponentChanges());
This needs to be named `COMPARE_COMPONENTS` with the helper method to get it renamed as well.

2024-04-23 00:12 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/api/stack/EmiRegistryAdapater.java
> +	EmiStack of(T t, @Nullable ComponentChanges componentChanges, long amount);
I think this shouldn't be nullable, I'll push a commit that has `EmiPort.emptyNbt()` which will return null in 1.20.4 and `ComponentChanges.EMPTY` in 1.20.5 which should reduce diff sizes (in additions to fixing the tag stack size issue).

2024-04-25 00:49 UTC, emilyploszaj approved these changes

2024-04-25 00:50 UTC, merged