Add dev mode nag for recipe IDs that should be synthetic
emilyploszaj/emi pull request #731
Opened 2024-10-03 18:46 UTC by Abbie5

Closes #730

Also changes some brewing recipe IDs to be synthetic.

2024-10-05 01:05 UTC, emilyploszaj requested changes
Thanks for the contribution and for finding all of the non-synthetic IDs remaining in EMI. Few crits then I'll merge.

2024-10-05 01:05 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/screen/WidgetGroup.java
> +			tooltip.addAll(EmiTooltip.splitTranslate("emi.dev.synthetic_id"));
Please add a more detailed tooltip for what's going on and why a dev should use a synthetic ID.

2024-10-05 01:05 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/runtime/dev/EmiDev.java
> +	public static Set<Identifier> missingRecipeIds = Set.of();
All instances of `missingRecipeIds` and similar should probably be renamed, they're not missing IDs (i.e. null). Can't think of a great name, but `incorrectRecipeIds` would be better, if you have something you think suits it better go for it.

2024-10-05 01:05 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/registry/EmiRecipes.java
> +					EmiReloadLog.warn("Recipe " + id + " not present in recipe manager. Consider prefixing its path with '/' to signify that it is synthetic.");
Nit: perhaps change to "Consider prefixing its path with '/' if it is synthetic"

2024-10-12 20:07 UTC, Abbie5 commented
Sorry for taking so long, I've made the requested changes now.

2024-10-13 18:28 UTC, emilyploszaj approved these changes

2024-10-13 18:28 UTC, merged