Update config UI to use modern look
emilyploszaj/emi pull request #757
Opened 2024-10-18 08:55 UTC by Abbie5

<img width="966" alt="emi-modern-config-look" src="https://github.com/user-attachments/assets/b34878dd-74c9-45e7-ba09-d2952c538c71">

2024-10-19 20:33 UTC, emilyploszaj requested changes
Looks nice! A little scary with the scissor but I'm sure it's fine. Just a few style crits.

2024-10-19 20:33 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/screen/widget/config/ConfigJumpButton.java
> +			context.matrices().translate(0, 0, 100);
EMI style doesn't do indenting like this, though I admit it is reasonable

2024-10-19 20:33 UTC, emilyploszaj commented on xplat/src/main/java/dev/emi/emi/screen/widget/config/ListWidget.java
> +			draw.drawTexture(
One line is fine for this instead of many.

2024-10-19 20:54 UTC, emilyploszaj approved these changes

2024-10-19 21:05 UTC, merged

2024-10-20 01:19 UTC, Abbie5 commented
I also said this in discord, but just to make sure: if possible this should not be merged to versions before 1.20.5. I made this PR to make EMI's config UI match vanilla's better on 1.20.5+, since Mojang changed it in 1.20.5 (that is the "modern look" I was referring to). It will likely look out-of-place on earlier versions, not to mention be difficult to port.

I should have mentioned this earlier, sorry.