Recipe Screenshots
emilyploszaj/emi pull request #99
Opened 2022-11-22 16:17 UTC by Kneelawk

# This PR
This PR adds the ability to take screenshots of recipes from EMI.

First, the screenshot button must be enabled from the EMI config file. Then, screenshots can be taken of recipes by clicking the screenshot button to the left of the recipe. The scale of screenshots is, by default, the current UI scale of the user's game, but can be set to a specific value in the EMI config file.

## Screenshots
![recipe-2022-11-22_07 00 00](https://user-images.githubusercontent.com/2180089/203347357-6ec72aec-2bec-4604-9c81-a291f3c6c1b3.png)
![2022-11-22_07 02 10](https://user-images.githubusercontent.com/2180089/203347979-f584da30-d3d1-4504-a21c-cb09f54af871.png)

2022-11-22 23:27 UTC, emilyploszaj requested changes
Overall looks pretty good, just a couple things I'd like to see resolved.

2022-11-22 23:27 UTC, emilyploszaj commented on src/main/java/dev/emi/emi/screen/RecipeScreen.java
> +					widgets.add(new RecipeScreenshotButtonWidget(-5 - 12, 0, r));
Screenshot button should be aligned to the bottom of the recipe like the buttons on the right, what do you think?

2022-11-22 23:27 UTC, emilyploszaj commented on src/main/java/dev/emi/emi/widget/RecipeScreenshotButtonWidget.java
> +		EmiScreenshotRecorder.saveScreenshot("recipe-", width, height,
The format of saving name by timestamp is... probably not ideal for most cases. I think it'd be better to save the file based on the recipe's identifier if possible, defaulting to a system like this if null. It is worth noting that EMI recipe identifiers can represent illegal paths like starting with `/` or having `//` in the body, so that character should be replaced with something else. For organization's sake, it should probably be a subfolder inside screenshots as well.

2022-11-22 23:27 UTC, emilyploszaj commented on src/main/java/dev/emi/emi/EmiScreenshotRecorder.java
> +
Initialization should contain a line somewhere invoking the following (as well as enabling blending) to prevent transparency issues discussed.
`RenderSystem.blendFuncSeparate(GLStateManager.SrcFactor.SRC_ALPHA, GLStateManager.DstFactor.ONE_MINUS_SRC_ALPHA, GLStateManager.SrcFactor.SRC_ALPHA, GLStateManager.DstFactor.ONE_MINUS_SRC_ALPHA);`

2022-11-23 02:35 UTC, Kneelawk commented on src/main/java/dev/emi/emi/EmiScreenshotRecorder.java
> +
I ended up fixing the fluid transparency issues by enabling blending and setting the blend func in the fluid stack renderer. See 743f41f.

2022-11-23 03:57 UTC, Kneelawk commented on src/main/java/dev/emi/emi/widget/RecipeScreenshotButtonWidget.java
> +		EmiScreenshotRecorder.saveScreenshot("recipe-", width, height,
Addressed by dd3b1a8 I believe.

2022-11-23 04:02 UTC, Kneelawk commented on src/main/java/dev/emi/emi/screen/RecipeScreen.java
> +					widgets.add(new RecipeScreenshotButtonWidget(-5 - 12, 0, r));
Addressed by 9325093.

2022-11-23 04:04 UTC, Kneelawk commented
Ok, I've changed the existing things, next I'm going to test with the Create and Botania widgets.

2022-11-23 05:01 UTC, emilyploszaj approved these changes

2022-11-23 05:01 UTC, Kneelawk commented
Ok, it works with Botania now.

Comparison: old (first) vs. new (second)
![mana_infusion_grass_seeds](https://user-images.githubusercontent.com/2180089/203472134-a092217f-ab79-4533-bb9b-e6081a8e2f3b.png)
![mana_infusion_grass_seeds_3](https://user-images.githubusercontent.com/2180089/203472095-a33fadda-e037-47e3-8db0-aff9e128323c.png)

2022-11-23 05:01 UTC, merged